name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
          description: Provide the Ingress URL
          required: true
          type: string
jobs:
  integration-test:
      needs: dev-deploy
      uses: ./.github/workflows/reusable-workflow.yml
      with:
        ingress-url: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}  
      runs-on: ubuntu-latest
      steps:
        - env:
            URL: ${{ inputs.ingress-url }}
          run: |
            curl https://$URL/live -s -k | jq -r .status | grep -i live
